services:
  ipr-zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ipr-network
    ports:
      - 32189:2181
    healthcheck:
      test: [ "CMD", "echo", "ruok", "|", "nc", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always

  ipr-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - ipr-zookeeper
    ports:
      - 29099:29092
      - 9099:9092
    networks:
      - ipr-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ipr-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29099
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 200000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 200000000
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/kafka/9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: on-failure

networks:
  ipr-network:
    driver: bridge
